baseurl = "https://leonwolf.dev"
title = "Leon Wolf"
languageCode = "de-de"
theme = "gokarna"
enableRobotsTXT = true
enableEmoji = true

[params]
avatarAltText = "avatar"
avatarSize = "size-m"
avatarURL = "/img/leon-wolf.jpg"
description = "iOS Developer @ JAKALA Germany"
footer = "Leon Wolf"
metaKeywords = ["Leon Wolf", "iOS Developer", "JAKALA Germany", "iOS Apps", "Scora", "Complication Compilation", "Apple Watch", "Swift", "Mobile Development", "App Development"]
showBackToTopButton = true                             # true or false for "back to top" button on posts and pages

socialIcons = [
    { name = "github", url = "https://github.com/leon-wolf" },
    # {name = "twitter", url = "https://example.com"},
    { name = "bluesky", url = "https://bsky.app/profile/leonwolf.dev" },
    { name = "linkedin", url = "https://www.linkedin.com/in/leon-wolf3103/" },
    # { name = "xing", url = "https://www.xing.com/profile/Leon_Wolf6" },
    { name = "stackoverflow", url = "https://stackoverflow.com/users/10005750/lwolf" },
    # {name = "dribbble", url = "https://example.com"},
    # {name = "instagram", url = "https://example.com"},
    # {name = "twitch", url = "https://example.com"},
    { name = "email", url = "mailto:leon@leonwolf.dev?subject=Kontakt über leonwolf.dev" },
]

# App Store and TestFlight URLs
[params.apps]
[params.apps.scora]
appStoreURL = "https://fli.so/scora"
testFlightURL = "https://fli.so/scora-tf"

[params.apps.complicationCompilation]
appStoreURL = "https://fli.so/comp-comp"
testFlightURL = "https://fli.so/comp-comp-tf"

# [services]
# [services.googleAnalytics]
# ID = "G-J7SRKMECR2"
# [services.disqus]
# shortname = "leonwolfdev"


[menu]
[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
name = "Apps"
pre = "<span data-feather='smartphone'></span>"
url = "/apps/"
weight = 2

# [[menu.main]]
# name = "Posts"
# pre = "<span data-feather='book'></span>"
# url = "/posts/"
# weight = 3

# [[menu.main]]
# name = "Projects"
# pre = "<span data-feather='code'></span>"
# url = "/projects/"
# weight = 4

# [[menu.main]]
# name = "Tags"
# pre = "<span data-feather='tag'></span>"
# url = "/tags/"
# weight = 5

[[menu.main]]
identifier = "buymeacoffee"
pre = "<span data-feather='coffee'></span>"
url = "https://buymeacoffee.com/leonwolf"
weight = 6

# [[menu.main]]
# identifier = "rss"
# pre = "<span data-feather='rss'></span>"
# url = "/index.xml"
# weight = 7

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 4
ordered = false

[minify]
minifyOutput = true
