baseurl      = "https://leonwolf.dev"
title        = "leonwolf.de"
languageCode = "de-de"
theme        = "hello-friend-ng"
paginate     = 10
googleAnalytics = "G-J7SRKMECR2"
enableRobotsTXT = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  [portrait]
   path = "img/leon-wolf.jpg"

  # Subtitle for home
  homeSubtitle = "iOS and Fullstack Web Developer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "leonwolf.dev - Personal Homepage"
  keywords = "homepage, iOS Developer, iOS, Developer, Swift, SwiftUI, UIKit, Web, VueJS, Javascript, JSDev, xCode"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "leonwolf.dev"
    subtitle = "iOS and Fullstack Web Developer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "leonwolf.dev"
      logoHomeLink = "/"
      logoCursorColor = "#006eff"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
   identifier = "CV"
   name       = "CV"
   url        = "files/CV-Leon Wolf.pdf"

[[params.social]]
  name = "github"
  url = "https://github.com/leon-wolf"

[[params.social]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/10005750/lwolf"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/leon-wolf3103/"

[[params.social]]
  name = "xing"
  url = "https://www.xing.com/profile/Leon_Wolf6"

[[params.social]]
  name = "email"
  url="mailto:leon@leonwolf.dev?subject=Kontakt über leonwolf.dev"

