baseurl      = "https://leonwolf.dev"
title        = "leonwolf.dev 2"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "iOS and Fullstack Web Developer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "leonwolf.dev"
    subtitle = "iOS and Fullstack Web Developer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "leonwolf.dev"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[[params.social]]
  name = "github"
  url = "https://github.com/leon-wolf"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/leon-wolf3103/"

[[params.social]]
  name = "xing"
  url = "https://www.xing.com/profile/Leon_Wolf6"

[[params.social]]
  name = "email"
  url="mailto:leon@leonwolf.dev?subject=Kontakt über leonwolf.dev"